// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queue_message.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from queue_message.proto</summary>
public static partial class QueueMessageReflection {

  #region Descriptor
  /// <summary>File descriptor for queue_message.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static QueueMessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNxdWV1ZV9tZXNzYWdlLnByb3RvGhBpb19tZXNzYWdlLnByb3RvIjsKDFF1",
          "ZXVlTWVzc2FnZRIbCgdwYWNrYWdlGAEgASgLMgouSW9NZXNzYWdlEg4KBnN0",
          "YXR1cxgCIAEoCWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::IoMessageReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::QueueMessage), global::QueueMessage.Parser, new[]{ "Package", "Status" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class QueueMessage : pb::IMessage<QueueMessage> {
  private static readonly pb::MessageParser<QueueMessage> _parser = new pb::MessageParser<QueueMessage>(() => new QueueMessage());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<QueueMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::QueueMessageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public QueueMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public QueueMessage(QueueMessage other) : this() {
    Package = other.package_ != null ? other.Package.Clone() : null;
    status_ = other.status_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public QueueMessage Clone() {
    return new QueueMessage(this);
  }

  /// <summary>Field number for the "package" field.</summary>
  public const int PackageFieldNumber = 1;
  private global::IoMessage package_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::IoMessage Package {
    get { return package_; }
    set {
      package_ = value;
    }
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 2;
  private string status_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Status {
    get { return status_; }
    set {
      status_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as QueueMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(QueueMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Package, other.Package)) return false;
    if (Status != other.Status) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (package_ != null) hash ^= Package.GetHashCode();
    if (Status.Length != 0) hash ^= Status.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (package_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Package);
    }
    if (Status.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Status);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (package_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Package);
    }
    if (Status.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Status);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(QueueMessage other) {
    if (other == null) {
      return;
    }
    if (other.package_ != null) {
      if (package_ == null) {
        package_ = new global::IoMessage();
      }
      Package.MergeFrom(other.Package);
    }
    if (other.Status.Length != 0) {
      Status = other.Status;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          if (package_ == null) {
            package_ = new global::IoMessage();
          }
          input.ReadMessage(package_);
          break;
        }
        case 18: {
          Status = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
